### ISSUE TITLE
showmount -e 127.0.0.1 complains unusual

### ISSUE THREAD

**Issue by fangyuxiangGL** [nfs-ganesha/ntirpc#146] opened 2018-09-04 07:31 UTC
root@aStor-7432:~# for i in {1..1000};do showmount -e 127.0.0.1 | grep reset ;done
rpc mount export: RPC: Unable to receive; errno = Connection reset by peer
rpc mount export: RPC: Unable to receive; errno = Connection reset by peer

root@aStor-7432:~# for i in {1..1000};do showmount -e 127.0.0.1 | grep reset ;done
rpc mount export: RPC: Unable to receive; errno = Connection reset by peer
rpc mount export: RPC: Unable to receive; errno = Connection reset by peer

@was4 @dang 

could you take a look ? thanks!

**Comment by was4** [comment] 2018-09-04 13:25
What does showmount have to do with rpc?

Methinks that you want to ask nfs-ganesha, where mounting is done.....

**Comment by dang** [comment] 2018-09-04 13:36
I'll look into this (as I work on both), but for the record, @fangyuxiangGL it's not necessary to tag us on these issues.  We already get notifications on all issues.

**Comment by fangyuxiangGL** [comment] 2018-09-05 02:28
@dang, got u, thanks

**Comment by fangyuxiangGL** [comment] 2018-09-05 03:42
@was4 

I just think this issue may be related to rpc.

**Comment by dang** [comment] 2018-09-05 16:42
What version of ganesha was this?  Also, what OS/distro?  I'm unable to reproduce here on 2.7-rc on Fedora.

**Comment by fangyuxiangGL** [comment] 2018-09-06 06:34
Build from source codes of ganesha 2.6.2 + libntirpc 1.6.2

**Comment by ffilz** [comment] 2024-05-14 20:39
I'm going to close this as it is years old and V2.6 is long out of support (we are now supporting V5.x and working V6).

**Closed as completed by ffilz** 2024-05-14 20:39 UTC
Labels: wontfix
