### ISSUE TITLE
./rpcping tcp 127.0.0.1 failed in ntirpc@4.0 on centos8_aarch64

### ISSUE THREAD

**Issue by Tom-python0121** [nfs-ganesha/ntirpc#250] opened 2021-12-28 10:11 UTC
Hello, I meet a problem :./rpcping tcp 127.0.0.1 failed in ntirpc@4.0 on centos8_aarch64 when I want to test it.
### Steps to reproduce the issue

```console
[root@localhost tests]# ls
CMakeFiles  Makefile  cmake_install.cmake  rpcping
[root@localhost tests]# ./rpcping
Usage: rpcping <raw|rdma|tcp|udp> <host> [--rpcbind] [--count=<n>] [--threads=<n>] [--workers=<n>] [--port=<n>] [--program=<n>] [--version=<n>] [--procedure=<n>]
[root@localhost tests]# ./rpcping raw 127.0.0.1
Segmentation fault (core dumped)
[root@localhost tests]# ./rpcping rdma 127.0.0.1
Segmentation fault (core dumped)
[root@localhost tests]# ./rpcping tcp 127.0.0.1
Segmentation fault (core dumped)
[root@localhost tests]# ./rpcping udp 127.0.0.1
Segmentation fault (core dumped)
```
Why did this error occur, and how did you fix it to make it work?

**Comment by Tom-python0121** [comment] 2021-12-29 08:21
The same error is reported on the x86_64 system. However, in ntirpc@3.2, both aarch64 and x86_64 tests are normal, as shown in the following figure: [root@localhost tests]# ./rpcping tcp 127.0.0.1
rpcping tcp 127.0.0.1 count=500 threads=1 workers=5 (port=2049 program=100003 version=3 procedure=0): failures 0 timeouts 500 mean 16.3974, total 16.3974

**Comment by Tom-python0121** [comment] 2021-12-29 08:22
Does the problem that memory leak occurs when source codes of other functions are added to ntirpc@3.2 or later? Segmentation fault (core dump)

**Comment by Tom-python0121** [comment] 2021-12-29 08:23
Does the problem that memory leak occurs when source codes of other functions are added to ntirpc@3.3 or later? Segmentation fault (core dump)

**Comment by ffilz** [comment] 2024-12-05 19:12
Is there a reason to use rpcping instead of rpcinfo which has "ping" capability also?

**Comment by ffilz** [comment] 2024-12-05 19:25
This is a duplicate of #220. Closing.

**Closed as completed by ffilz** 2024-12-05 19:25 UTC
Labels: duplicate
